const RAW_EXTRA_SEEDED_TOPICS = [
  {
    "id": "topic-regulations-2",
    "title": "Topic 2: Regulations",
    "source": "Topic 2.pdf",
    "words": [
      {
        "english": "attire",
        "partOfSpeech": "n.",
        "vietnamese": "quần áo, cách ăn mặc",
        "ipaUs": "/əˈtaɪr/",
        "ipaUk": "/əˈtaɪr/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "concern",
        "partOfSpeech": "n.",
        "vietnamese": "sự lo lắng, mối quan ngại",
        "ipaUs": "/kənˈsɝːn/",
        "ipaUk": "/kənˈsɝːn/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "concern",
        "partOfSpeech": "v.",
        "vietnamese": "lo lắng, bận tâm; ảnh hưởng; liên quan",
        "ipaUs": "/kənˈsɝːn/",
        "ipaUk": "/kənˈsɝːn/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "exception",
        "partOfSpeech": "n.",
        "vietnamese": "ngoại lệ",
        "ipaUs": "/ɪkˈsep.ʃən/",
        "ipaUk": "/ɪkˈsep.ʃən/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "comply",
        "partOfSpeech": "v.",
        "vietnamese": "tuân thủ, tuân theo",
        "ipaUs": "/kəmˈplaɪ/",
        "ipaUk": "/kəmˈplaɪ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "regulation",
        "partOfSpeech": "n.",
        "vietnamese": "quy định, quy tắc",
        "ipaUs": "/ˌreɡ.jəˈleɪ.ʃən/",
        "ipaUk": "/ˌreɡ.jəˈleɪ.ʃən/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "policy",
        "partOfSpeech": "n.",
        "vietnamese": "quy chế, chính sách",
        "ipaUs": "/ˈpɑː.lə.si/",
        "ipaUk": "/ˈpɑː.lə.si/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "severely",
        "partOfSpeech": "adv.",
        "vietnamese": "nghiêm khắc, khắt khe; gay gắt",
        "ipaUs": "/səˈvɪr.li/",
        "ipaUk": "/səˈvɪr.li/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "refrain",
        "partOfSpeech": "v.",
        "vietnamese": "kiềm chế, hạn chế",
        "ipaUs": "/rɪˈfreɪn/",
        "ipaUk": "/rɪˈfreɪn/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "access",
        "partOfSpeech": "n.",
        "vietnamese": "quyền truy cập, sự lui tới, đường vào",
        "ipaUs": "/ˈæk.ses/",
        "ipaUk": "/ˈæk.ses/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "access",
        "partOfSpeech": "v.",
        "vietnamese": "truy cập, tiếp cận",
        "ipaUs": "/ˈæk.ses/",
        "ipaUk": "/ˈæk.ses/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "thoroughly",
        "partOfSpeech": "adv.",
        "vietnamese": "một cách kỹ lưỡng, hoàn toàn",
        "ipaUs": "/ˈθɝː.ə.li/ /ˈθɝː.oʊ.li/",
        "ipaUk": "/ˈθɝː.ə.li/ /ˈθɝː.oʊ.li/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "revise",
        "partOfSpeech": "v.",
        "vietnamese": "sửa đổi, thay đổi, duyệt lại",
        "ipaUs": "/rɪˈvaɪz/",
        "ipaUk": "/rɪˈvaɪz/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "approval",
        "partOfSpeech": "n.",
        "vietnamese": "sự chấp thuận, sự phê duyệt",
        "ipaUs": "/əˈpruː.vəl/",
        "ipaUk": "/əˈpruː.vəl/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "form",
        "partOfSpeech": "n.",
        "vietnamese": "kiểu, loại, hình thức, biểu mẫu",
        "ipaUs": "/fɔːrm/",
        "ipaUk": "/fɔːrm/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "form",
        "partOfSpeech": "v.",
        "vietnamese": "tạo thành, định hình",
        "ipaUs": "/fɔːrm/",
        "ipaUk": "/fɔːrm/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "immediately",
        "partOfSpeech": "adv.",
        "vietnamese": "ngay lập tức",
        "ipaUs": "/ɪˈmiː.di.ət.li/",
        "ipaUk": "/ɪˈmiː.di.ət.li/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "procedure",
        "partOfSpeech": "n.",
        "vietnamese": "thủ tục, quy trình",
        "ipaUs": "/prəˈsiː.dʒɚ/",
        "ipaUk": "/prəˈsiː.dʒɚ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "negative",
        "partOfSpeech": "n./adj.",
        "vietnamese": "điều tiêu cực; tiêu cực, bi quan",
        "ipaUs": "/ˈneɡ.ə.tɪv/",
        "ipaUk": "/ˈneɡ.ə.tɪv/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "mandate",
        "partOfSpeech": "v.",
        "vietnamese": "ra lệnh, ủy quyền, ủy thác",
        "ipaUs": "/ˈmæn.deɪt/",
        "ipaUk": "/ˈmæn.deɪt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "mandate",
        "partOfSpeech": "n.",
        "vietnamese": "mệnh lệnh, sự ủy thác",
        "ipaUs": "/ˈmæn.deɪt/",
        "ipaUk": "/ˈmæn.deɪt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "effect",
        "partOfSpeech": "n.",
        "vietnamese": "hiệu ứng, hiệu quả, hiệu lực",
        "ipaUs": "/əˈfekt/",
        "ipaUk": "/əˈfekt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "effect",
        "partOfSpeech": "v.",
        "vietnamese": "thực hiện, đem lại",
        "ipaUs": "/əˈfekt/",
        "ipaUk": "/əˈfekt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "drastically",
        "partOfSpeech": "adv.",
        "vietnamese": "mạnh mẽ, quyết liệt, triệt để",
        "ipaUs": "/ˈdræs.tɪ.kəl.i/",
        "ipaUk": "/ˈdræs.tɪ.kəl.i/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "according to",
        "partOfSpeech": "prep.",
        "vietnamese": "theo, căn cứ theo",
        "ipaUs": "/əˈkɔːr.dɪŋ ˌtuː/",
        "ipaUk": "/əˈkɔːr.dɪŋ ˌtuː/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "standard",
        "partOfSpeech": "n.",
        "vietnamese": "tiêu chuẩn, chuẩn, trình độ",
        "ipaUs": "/ˈstæn.dɚd/",
        "ipaUk": "/ˈstæn.dɚd/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "constant",
        "partOfSpeech": "adj.",
        "vietnamese": "liên tục, không ngớt, không đổi",
        "ipaUs": "/ˈkɑːn.stənt/",
        "ipaUk": "/ˈkɑːn.stənt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "obligation",
        "partOfSpeech": "n.",
        "vietnamese": "nghĩa vụ, trách nhiệm",
        "ipaUs": "/ˌɑː.bləˈɡeɪ.ʃən/",
        "ipaUk": "/ˌɑː.bləˈɡeɪ.ʃən/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "authorize",
        "partOfSpeech": "v.",
        "vietnamese": "ủy quyền, cho phép",
        "ipaUs": "/ˈɑː.θɚ.aɪz/",
        "ipaUk": "/ˈɑː.θɚ.aɪz/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "prohibit",
        "partOfSpeech": "v.",
        "vietnamese": "ngăn cấm, ngăn chặn, không cho phép",
        "ipaUs": "/prəˈhɪb.ɪt/",
        "ipaUk": "/prəˈhɪb.ɪt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "habit",
        "partOfSpeech": "n.",
        "vietnamese": "thói quen, tập quán",
        "ipaUs": "/ˈhæb.ɪt/",
        "ipaUk": "/ˈhæb.ɪt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "restrict",
        "partOfSpeech": "v.",
        "vietnamese": "giới hạn, hạn chế",
        "ipaUs": "/rɪˈstrɪkt/",
        "ipaUk": "/rɪˈstrɪkt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "code",
        "partOfSpeech": "n.",
        "vietnamese": "quy định, bộ luật",
        "ipaUs": "/koʊd/",
        "ipaUk": "/koʊd/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "adhere",
        "partOfSpeech": "v.",
        "vietnamese": "bám sát, tuân thủ",
        "ipaUs": "/ədˈhɪr/",
        "ipaUk": "/ədˈhɪr/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "permission",
        "partOfSpeech": "n.",
        "vietnamese": "sự cho phép",
        "ipaUs": "/pɚˈmɪʃ.ən/",
        "ipaUk": "/pɚˈmɪʃ.ən/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "approach",
        "partOfSpeech": "n.",
        "vietnamese": "cách tiếp cận, phương pháp xử lý",
        "ipaUs": "/əˈproʊtʃ/",
        "ipaUk": "/əˈproʊtʃ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "act",
        "partOfSpeech": "n.",
        "vietnamese": "việc, hành động; đạo luật",
        "ipaUs": "/ækt/",
        "ipaUk": "/ækt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "approach",
        "partOfSpeech": "v.",
        "vietnamese": "tiếp cận",
        "ipaUs": "/əˈproʊtʃ/",
        "ipaUk": "/əˈproʊtʃ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "inspection",
        "partOfSpeech": "n.",
        "vietnamese": "sự kiểm tra, sự thanh tra",
        "ipaUs": "/ɪnˈspek.ʃən/",
        "ipaUk": "/ɪnˈspek.ʃən/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "arrangement",
        "partOfSpeech": "n.",
        "vietnamese": "sự sắp đặt, sự sắp xếp, sự chuẩn bị",
        "ipaUs": "/əˈreɪndʒ.mənt/",
        "ipaUk": "/əˈreɪndʒ.mənt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "enable",
        "partOfSpeech": "v.",
        "vietnamese": "làm cho có thể, cho phép",
        "ipaUs": "/ɪˈneɪ.bəl/",
        "ipaUk": "/ɪˈneɪ.bəl/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "act",
        "partOfSpeech": "v.",
        "vietnamese": "hành động, đưa ra quyết định",
        "ipaUs": "/ækt/",
        "ipaUk": "/ækt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "legislation",
        "partOfSpeech": "n.",
        "vietnamese": "pháp luật, sự làm luật",
        "ipaUs": "/ˌledʒ.əˈsleɪ.ʃən/",
        "ipaUk": "/ˌledʒ.əˈsleɪ.ʃən/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "compensation",
        "partOfSpeech": "n.",
        "vietnamese": "sự đền bù, sự bồi thường",
        "ipaUs": "/ˌkɑːm.penˈseɪ.ʃən/",
        "ipaUk": "/ˌkɑːm.penˈseɪ.ʃən/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "ban",
        "partOfSpeech": "n.",
        "vietnamese": "lệnh cấm, sự cấm đoán",
        "ipaUs": "/bæn/",
        "ipaUk": "/bæn/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "ban",
        "partOfSpeech": "v.",
        "vietnamese": "cấm",
        "ipaUs": "/bæn/",
        "ipaUk": "/bæn/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "abolish",
        "partOfSpeech": "v.",
        "vietnamese": "thủ tiêu, bãi bỏ, hủy bỏ",
        "ipaUs": "/əˈbɑː.lɪʃ/",
        "ipaUk": "/əˈbɑː.lɪʃ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "enforce",
        "partOfSpeech": "v.",
        "vietnamese": "thi hành, thúc ép, làm cho có hiệu lực",
        "ipaUs": "/ɪnˈfɔːrs/",
        "ipaUk": "/ɪnˈfɔːrs/",
        "related": "",
        "example": "",
        "exampleVi": ""
      }
    ]
  },
  {
    "id": "topic-office-work-3",
    "title": "Topic 3: Office Work",
    "source": "Topic 3.pdf",
    "words": [
      {
        "english": "accustomed",
        "partOfSpeech": "adj.",
        "vietnamese": "quen với, thành thói quen",
        "ipaUs": "/əˈkʌs.təmd/",
        "ipaUk": "/əˈkʌs.təmd/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "demanding",
        "partOfSpeech": "adj.",
        "vietnamese": "đòi hỏi khắt khe",
        "ipaUs": "/dɪˈmæn.dɪŋ/",
        "ipaUk": "/dɪˈmæn.dɪŋ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "colleague",
        "partOfSpeech": "n.",
        "vietnamese": "đồng nghiệp",
        "ipaUs": "/ˈkɑː.liːɡ/",
        "ipaUk": "/ˈkɑː.liːɡ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "division",
        "partOfSpeech": "n.",
        "vietnamese": "bộ phận, sự phân chia",
        "ipaUs": "/dɪˈvɪʒ.ən/",
        "ipaUk": "/dɪˈvɪʒ.ən/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "request",
        "partOfSpeech": "n.",
        "vietnamese": "lời yêu cầu, thỉnh cầu",
        "ipaUs": "/rɪˈkwest/",
        "ipaUk": "/rɪˈkwest/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "efficiently",
        "partOfSpeech": "adv.",
        "vietnamese": "một cách hiệu quả",
        "ipaUs": "/ɪˈfɪʃ.ənt.li/",
        "ipaUk": "/ɪˈfɪʃ.ənt.li/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "submit",
        "partOfSpeech": "v.",
        "vietnamese": "đệ trình, nộp",
        "ipaUs": "/səbˈmɪt/",
        "ipaUk": "/səbˈmɪt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "directly",
        "partOfSpeech": "adv.",
        "vietnamese": "trực tiếp, thẳng, ngay",
        "ipaUs": "/daɪˈrekt.li/ /dɪˈrekt.li/",
        "ipaUk": "/daɪˈrekt.li/ /dɪˈrekt.li/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "remind",
        "partOfSpeech": "v.",
        "vietnamese": "nhắc nhở",
        "ipaUs": "/rɪˈmaɪnd/",
        "ipaUk": "/rɪˈmaɪnd/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "instruct",
        "partOfSpeech": "v.",
        "vietnamese": "hướng dẫn, chỉ thị, dạy",
        "ipaUs": "/ɪnˈstrʌkt/",
        "ipaUk": "/ɪnˈstrʌkt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "sample",
        "partOfSpeech": "n.",
        "vietnamese": "mẫu, mẫu thử",
        "ipaUs": "/ˈsæm.pəl/",
        "ipaUk": "/ˈsæm.pəl/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "notify",
        "partOfSpeech": "v.",
        "vietnamese": "thông báo, cho biết",
        "ipaUs": "/ˈnoʊ.tə.faɪ/",
        "ipaUk": "/ˈnoʊ.tə.faɪ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "perform",
        "partOfSpeech": "v.",
        "vietnamese": "thi hành, thực hiện, hoạt động",
        "ipaUs": "/pɚˈfɔːrm/",
        "ipaUk": "/pɚˈfɔːrm/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "assignment",
        "partOfSpeech": "n.",
        "vietnamese": "nhiệm vụ, bài tập, việc được giao",
        "ipaUs": "/əˈsaɪn.mənt/",
        "ipaUk": "/əˈsaɪn.mənt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "entire",
        "partOfSpeech": "adj.",
        "vietnamese": "trọn vẹn, hoàn toàn",
        "ipaUs": "/ɪnˈtaɪr/",
        "ipaUk": "/ɪnˈtaɪr/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "extension",
        "partOfSpeech": "n.",
        "vietnamese": "sự gia hạn, sự kéo dài, sự mở rộng",
        "ipaUs": "/ɪkˈsten.ʃən/",
        "ipaUk": "/ɪkˈsten.ʃən/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "attendance",
        "partOfSpeech": "n.",
        "vietnamese": "sự tham gia, sự có mặt",
        "ipaUs": "/əˈten.dəns/",
        "ipaUk": "/əˈten.dəns/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "absolutely",
        "partOfSpeech": "adv.",
        "vietnamese": "hoàn toàn, chắc chắn, nhất định",
        "ipaUs": "/ˌæb.səˈluːt.li/",
        "ipaUk": "/ˌæb.səˈluːt.li/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "delegate",
        "partOfSpeech": "v.",
        "vietnamese": "ủy quyền, ủy thác, giao phó",
        "ipaUs": "/ˈdel.ə.ɡət/",
        "ipaUk": "/ˈdel.ə.ɡət/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "attentively",
        "partOfSpeech": "adv.",
        "vietnamese": "chăm chú, thận trọng",
        "ipaUs": "/əˈten.tɪv.li/",
        "ipaUk": "/əˈten.tɪv.li/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "supervision",
        "partOfSpeech": "n.",
        "vietnamese": "sự giám sát",
        "ipaUs": "/ˌsuː.pɚˈvɪʒ.ən/",
        "ipaUk": "/ˌsuː.pɚˈvɪʒ.ən/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "revision",
        "partOfSpeech": "n.",
        "vietnamese": "sự sửa lại, sự duyệt lại",
        "ipaUs": "/rɪˈvɪʒ.ən/",
        "ipaUk": "/rɪˈvɪʒ.ən/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "reluctantly",
        "partOfSpeech": "adv.",
        "vietnamese": "miễn cưỡng, bất đắc dĩ",
        "ipaUs": "/rɪˈlʌk.tənt.li/",
        "ipaUk": "/rɪˈlʌk.tənt.li/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "acquaint",
        "partOfSpeech": "v.",
        "vietnamese": "làm quen với, làm cho ai quen với",
        "ipaUs": "/əˈkweɪnt ˌwɪð, -ˌwɪθ/",
        "ipaUk": "/əˈkweɪnt ˌwɪð, -ˌwɪθ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "convey",
        "partOfSpeech": "v.",
        "vietnamese": "truyền đạt, vận chuyển",
        "ipaUs": "/ kənˈveɪ /",
        "ipaUk": "/ kənˈveɪ /",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "check",
        "partOfSpeech": "v.",
        "vietnamese": "kiểm tra, xem xét, xác nhận",
        "ipaUs": "/tʃek/",
        "ipaUk": "/tʃek/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "file",
        "partOfSpeech": "v.",
        "vietnamese": "sắp xếp, lưu giữ; trình lên, đưa ra",
        "ipaUs": "/faɪl/",
        "ipaUk": "/faɪl/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "oversee",
        "partOfSpeech": "v.",
        "vietnamese": "quan sát, giám sát",
        "ipaUs": "/ˌoʊ.vɚˈsiː/",
        "ipaUk": "/ˌoʊ.vɚˈsiː/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "concentrate",
        "partOfSpeech": "v.",
        "vietnamese": "tập trung, chú tâm",
        "ipaUs": "/ˈkɑːn.sən.treɪt/",
        "ipaUk": "/ˈkɑːn.sən.treɪt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "corporation",
        "partOfSpeech": "n.",
        "vietnamese": "công ty, tập đoàn",
        "ipaUs": "/ˌkɔːr.pəˈreɪ.ʃən/",
        "ipaUk": "/ˌkɔːr.pəˈreɪ.ʃən/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "manage",
        "partOfSpeech": "v.",
        "vietnamese": "quản lý, xoay sở, giải quyết được",
        "ipaUs": "/ˈmæn.ədʒ/",
        "ipaUk": "/ˈmæn.ədʒ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "monitor",
        "partOfSpeech": "v.",
        "vietnamese": "giám sát, theo dõi",
        "ipaUs": "/ˈmɑː.nə.tɚ/",
        "ipaUk": "/ˈmɑː.nə.tɚ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "monitor",
        "partOfSpeech": "n.",
        "vietnamese": "màn hình",
        "ipaUs": "/ˈmɑː.nə.tɚ/",
        "ipaUk": "/ˈmɑː.nə.tɚ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "deserve",
        "partOfSpeech": "v.",
        "vietnamese": "đáng, xứng đáng",
        "ipaUs": "/dɪˈzɝːv/",
        "ipaUk": "/dɪˈzɝːv/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "release",
        "partOfSpeech": "v.",
        "vietnamese": "phát hành, phóng thích, làm nhẹ bớt",
        "ipaUs": "/rɪˈliːs/",
        "ipaUk": "/rɪˈliːs/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "release",
        "partOfSpeech": "n.",
        "vietnamese": "sự phát hành, sự ra mắt sản phẩm",
        "ipaUs": "/rɪˈliːs/",
        "ipaUk": "/rɪˈliːs/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "electronically",
        "partOfSpeech": "adv.",
        "vietnamese": "bằng điện tử",
        "ipaUs": "/iˌlekˈtrɑː.nɪ.kəl.i/",
        "ipaUk": "/iˌlekˈtrɑː.nɪ.kəl.i/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "workshop",
        "partOfSpeech": "n.",
        "vietnamese": "hội thảo, buổi đào tạo",
        "ipaUs": "/ˈwɝːk.ʃɑːp/",
        "ipaUk": "/ˈwɝːk.ʃɑːp/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "headquarters",
        "partOfSpeech": "n.",
        "vietnamese": "trụ sở chính",
        "ipaUs": "/ˈhedˌkwɔːr.tɚz/",
        "ipaUk": "/ˈhedˌkwɔːr.tɚz/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "involved",
        "partOfSpeech": "adj.",
        "vietnamese": "có tham gia vào, có liên quan",
        "ipaUs": "/ɪnˈvɑːlvd/",
        "ipaUk": "/ɪnˈvɑːlvd/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "lax",
        "partOfSpeech": "adj.",
        "vietnamese": "không cẩn thận, thiếu nghiêm túc",
        "ipaUs": "/læks/",
        "ipaUk": "/læks/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "procrastinate",
        "partOfSpeech": "v.",
        "vietnamese": "trì hoãn, chần chừ",
        "ipaUs": "/proʊˈkræs.tə.neɪt/",
        "ipaUk": "/proʊˈkræs.tə.neɪt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "assume",
        "partOfSpeech": "v.",
        "vietnamese": "cho rằng, giả sử; đảm đương",
        "ipaUs": "/əˈsuːm/",
        "ipaUk": "/əˈsuːm/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "combined",
        "partOfSpeech": "adj.",
        "vietnamese": "được kết hợp, chung, tổng hợp",
        "ipaUs": "/kəmˈbaɪnd/",
        "ipaUk": "/kəmˈbaɪnd/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "voluntarily",
        "partOfSpeech": "adv.",
        "vietnamese": "tự nguyện",
        "ipaUs": "/ˈvɑː.lən.ter.əl.i/",
        "ipaUk": "/ˈvɑː.lən.ter.əl.i/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "assist",
        "partOfSpeech": "v.",
        "vietnamese": "trợ giúp, hỗ trợ",
        "ipaUs": "/əˈsɪst/",
        "ipaUk": "/əˈsɪst/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "satisfied",
        "partOfSpeech": "adj.",
        "vietnamese": "hài lòng, thỏa mãn",
        "ipaUs": "/ˈsæt.ɪs.faɪd/",
        "ipaUk": "/ˈsæt.ɪs.faɪd/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "responsible",
        "partOfSpeech": "adj.",
        "vietnamese": "có trách nhiệm, chịu trách nhiệm",
        "ipaUs": "/rɪˈspɑːn.sə.bəl/",
        "ipaUk": "/rɪˈspɑːn.sə.bəl/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "occasionally",
        "partOfSpeech": "adv.",
        "vietnamese": "thỉnh thoảng, đôi khi",
        "ipaUs": "/əˈkeɪ.ʒən.əl.i/ /əˈkeɪʒ.nəl.i/",
        "ipaUk": "/əˈkeɪ.ʒən.əl.i/ /əˈkeɪʒ.nəl.i/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "employee",
        "partOfSpeech": "n.",
        "vietnamese": "nhân viên, người lao động",
        "ipaUs": "/ɪmˈplɔɪ.iː/ /ˌem.plɔɪˈiː/",
        "ipaUk": "/ɪmˈplɔɪ.iː/ /ˌem.plɔɪˈiː/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "conduct",
        "partOfSpeech": "v.",
        "vietnamese": "tiến hành, chỉ đạo, điều khiển",
        "ipaUs": "/kənˈdʌkt/",
        "ipaUk": "/kənˈdʌkt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "agree",
        "partOfSpeech": "v.",
        "vietnamese": "đồng ý, nhất trí",
        "ipaUs": "/əˈɡriː/",
        "ipaUk": "/əˈɡriː/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "supervise",
        "partOfSpeech": "v.",
        "vietnamese": "giám sát",
        "ipaUs": "/ˈsuː.pɚ.vaɪz/",
        "ipaUk": "/ˈsuː.pɚ.vaɪz/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "direct",
        "partOfSpeech": "v.",
        "vietnamese": "hướng dẫn, chỉ đạo",
        "ipaUs": "/daɪˈrekt/ /dɪˈrekt/",
        "ipaUk": "/daɪˈrekt/ /dɪˈrekt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "assign",
        "partOfSpeech": "v.",
        "vietnamese": "phân công, bổ nhiệm",
        "ipaUs": "/əˈsaɪn/",
        "ipaUk": "/əˈsaɪn/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "formal",
        "partOfSpeech": "adj.",
        "vietnamese": "trang trọng, chính thức",
        "ipaUs": "/ˈfɔːr.məl/",
        "ipaUk": "/ˈfɔːr.məl/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "remove",
        "partOfSpeech": "v.",
        "vietnamese": "xóa, dẹp; đuổi, cách chức",
        "ipaUs": "/rɪˈmuːv/",
        "ipaUk": "/rɪˈmuːv/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "collect",
        "partOfSpeech": "v.",
        "vietnamese": "thu thập, tập hợp",
        "ipaUs": "/kəˈlekt/",
        "ipaUk": "/kəˈlekt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "coordinate",
        "partOfSpeech": "v.",
        "vietnamese": "điều phối, kết hợp",
        "ipaUs": "/koʊˈɔːr.dən.eɪt/",
        "ipaUk": "/koʊˈɔːr.dən.eɪt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "hardly",
        "partOfSpeech": "adv.",
        "vietnamese": "hiếm khi, gần như không",
        "ipaUs": "/ˈhɑːrd.li/",
        "ipaUk": "/ˈhɑːrd.li/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "leading",
        "partOfSpeech": "adj.",
        "vietnamese": "dẫn đầu, tiên phong, hàng đầu",
        "ipaUs": "/ˈliː.dɪŋ/",
        "ipaUk": "/ˈliː.dɪŋ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "exclusive",
        "partOfSpeech": "adj.",
        "vietnamese": "riêng biệt, độc quyền",
        "ipaUs": "/ɪkˈskluː.sɪv/",
        "ipaUk": "/ɪkˈskluː.sɪv/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "intention",
        "partOfSpeech": "n.",
        "vietnamese": "ý định, mục đích, ý muốn",
        "ipaUs": "/ɪnˈten.ʃən/",
        "ipaUk": "/ɪnˈten.ʃən/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "disturbing",
        "partOfSpeech": "adj.",
        "vietnamese": "làm nhiễu loạn, làm xáo trộn",
        "ipaUs": "/dɪˈstɝː.bɪŋ/",
        "ipaUk": "/dɪˈstɝː.bɪŋ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "foster",
        "partOfSpeech": "v.",
        "vietnamese": "thúc đẩy, bồi dưỡng, bồi đắp",
        "ipaUs": "/ˈfɑː.stɚ/",
        "ipaUk": "/ˈfɑː.stɚ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "skillfully",
        "partOfSpeech": "adv.",
        "vietnamese": "thành thạo, khéo léo",
        "ipaUs": "/ˈskɪl.fəl.i/",
        "ipaUk": "/ˈskɪl.fəl.i/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "widely",
        "partOfSpeech": "adv.",
        "vietnamese": "rộng rãi, nhiều, xa",
        "ipaUs": "/ˈwaɪd.li/",
        "ipaUk": "/ˈwaɪd.li/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "accomplish",
        "partOfSpeech": "v.",
        "vietnamese": "hoàn thành, làm xong, đạt được",
        "ipaUs": "/əˈkɑːm.plɪʃ/",
        "ipaUk": "/əˈkɑːm.plɪʃ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "undertake",
        "partOfSpeech": "v.",
        "vietnamese": "đảm nhận, tiếp quản",
        "ipaUs": "/ˌʌn.dɚˈteɪk/",
        "ipaUk": "/ˌʌn.dɚˈteɪk/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "manner",
        "partOfSpeech": "n.",
        "vietnamese": "cách, lối; thái độ, cử chỉ",
        "ipaUs": "/ˈmæn.ɚ/",
        "ipaUk": "/ˈmæn.ɚ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "neutrality",
        "partOfSpeech": "n.",
        "vietnamese": "tính trung lập, thái độ trung lập",
        "ipaUs": "/nuːˈtræl.ə.ti/",
        "ipaUk": "/nuːˈtræl.ə.ti/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "personnel",
        "partOfSpeech": "n.",
        "vietnamese": "nhân viên, công chức",
        "ipaUs": "/ˌpɝː.sənˈel/",
        "ipaUk": "/ˌpɝː.sənˈel/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "confidential",
        "partOfSpeech": "adj.",
        "vietnamese": "bí mật, cẩn mật, tuyệt mật",
        "ipaUs": "/ˌkɑːn.fəˈden.ʃəl/",
        "ipaUk": "/ˌkɑːn.fəˈden.ʃəl/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "abstract",
        "partOfSpeech": "adj.",
        "vietnamese": "trừu tượng, mơ hồ",
        "ipaUs": "/ˈæb.strækt/",
        "ipaUk": "/ˈæb.strækt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "directory",
        "partOfSpeech": "n.",
        "vietnamese": "danh bạ, sổ địa chỉ",
        "ipaUs": "/dɪˈrek.tɚ.i/ /daɪˈrek.tɚ.i/",
        "ipaUk": "/dɪˈrek.tɚ.i/ /daɪˈrek.tɚ.i/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "adjust",
        "partOfSpeech": "v.",
        "vietnamese": "điều chỉnh, làm cho thích hợp",
        "ipaUs": "/əˈdʒʌst/",
        "ipaUk": "/əˈdʒʌst/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "transform",
        "partOfSpeech": "v.",
        "vietnamese": "biến đổi, thay đổi",
        "ipaUs": "/trænsˈfɔːrm/",
        "ipaUk": "/trænsˈfɔːrm/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "respectful",
        "partOfSpeech": "adj.",
        "vietnamese": "tôn trọng, lễ phép, kính cẩn",
        "ipaUs": "/rɪˈspekt.fəl/",
        "ipaUk": "/rɪˈspekt.fəl/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "duplicate",
        "partOfSpeech": "n.",
        "vietnamese": "bản sao",
        "ipaUs": "/ˈduː.plə.keɪt/",
        "ipaUk": "/ˈduː.plə.keɪt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "contrary",
        "partOfSpeech": "n.",
        "vietnamese": "sự trái ngược, điều ngược lại",
        "ipaUs": "/ˈkɑːn.tre.ri/",
        "ipaUk": "/ˈkɑːn.tre.ri/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "accountable",
        "partOfSpeech": "adj.",
        "vietnamese": "chịu trách nhiệm, có thể giải thích được",
        "ipaUs": "/əˈkaʊn.tə.bəl/",
        "ipaUk": "/əˈkaʊn.tə.bəl/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "engage",
        "partOfSpeech": "v.",
        "vietnamese": "tham gia, cam kết, thu hút",
        "ipaUs": "/ɪnˈɡeɪdʒ/",
        "ipaUk": "/ɪnˈɡeɪdʒ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "timely",
        "partOfSpeech": "adj./adv.",
        "vietnamese": "kịp thời, đúng lúc",
        "ipaUs": "/ˈtaɪm.li/",
        "ipaUk": "/ˈtaɪm.li/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "realistically",
        "partOfSpeech": "adv.",
        "vietnamese": "theo thực tế, thực tế là",
        "ipaUs": "/ˌriː.əˈlɪs.tɪ.kəl.i/",
        "ipaUk": "/ˌriː.əˈlɪs.tɪ.kəl.i/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "promptly",
        "partOfSpeech": "adv.",
        "vietnamese": "nhanh chóng, ngay lập tức",
        "ipaUs": "/ˈprɑːmpt.li/",
        "ipaUk": "/ˈprɑːmpt.li/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "accessible",
        "partOfSpeech": "adj.",
        "vietnamese": "có thể truy cập, có thể tiếp cận được",
        "ipaUs": "/əkˈses.ə.bəl/",
        "ipaUk": "/əkˈses.ə.bəl/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "implement",
        "partOfSpeech": "v.",
        "vietnamese": "thi hành, thực hiện",
        "ipaUs": "/ˈɪm.plə.ment/",
        "ipaUk": "/ˈɪm.plə.ment/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "feedback",
        "partOfSpeech": "n.",
        "vietnamese": "phản hồi, ý kiến nhận xét",
        "ipaUs": "/ˈfiːd.bæk/",
        "ipaUk": "/ˈfiːd.bæk/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "outstanding",
        "partOfSpeech": "adj.",
        "vietnamese": "nổi bật, đáng chú ý; còn tồn tại",
        "ipaUs": "/ˌaʊtˈstæn.dɪŋ/",
        "ipaUk": "/ˌaʊtˈstæn.dɪŋ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "inform",
        "partOfSpeech": "v.",
        "vietnamese": "thông báo, báo tin",
        "ipaUs": "/ɪnˈfɔːrm/",
        "ipaUk": "/ɪnˈfɔːrm/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "announcement",
        "partOfSpeech": "n.",
        "vietnamese": "thông cáo, thông báo",
        "ipaUs": "/əˈnaʊns.mənt/",
        "ipaUk": "/əˈnaʊns.mənt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "fulfill",
        "partOfSpeech": "v.",
        "vietnamese": "hoàn thành, đáp ứng, thực thi",
        "ipaUs": "/fʊlˈfɪl/",
        "ipaUk": "/fʊlˈfɪl/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "outline",
        "partOfSpeech": "n.",
        "vietnamese": "bản thảo, nét phác thảo, dàn bài",
        "ipaUs": "/ˈaʊt.laɪn/",
        "ipaUk": "/ˈaʊt.laɪn/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "outline",
        "partOfSpeech": "v.",
        "vietnamese": "vẽ phác thảo, vạch ra ý chính",
        "ipaUs": "/ˈaʊt.laɪn/",
        "ipaUk": "/ˈaʊt.laɪn/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "explain",
        "partOfSpeech": "v.",
        "vietnamese": "giải thích, giảng giải",
        "ipaUs": "/ɪkˈspleɪn/",
        "ipaUk": "/ɪkˈspleɪn/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "overview",
        "partOfSpeech": "n.",
        "vietnamese": "tổng quát, khái quát",
        "ipaUs": "/ˈoʊ.vɚ.vjuː/",
        "ipaUk": "/ˈoʊ.vɚ.vjuː/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "matter",
        "partOfSpeech": "n.",
        "vietnamese": "vấn đề, công việc",
        "ipaUs": "/ˈmæt.ɚ/",
        "ipaUk": "/ˈmæt.ɚ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "replacement",
        "partOfSpeech": "n.",
        "vietnamese": "sự thay thế, người/vật thay thế",
        "ipaUs": "/rɪˈpleɪs.mənt/",
        "ipaUk": "/rɪˈpleɪs.mənt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "expertise",
        "partOfSpeech": "n.",
        "vietnamese": "sự tinh thông, kỹ năng chuyên môn",
        "ipaUs": "/ˌek.spɝːˈtiːz/",
        "ipaUk": "/ˌek.spɝːˈtiːz/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "demonstrate",
        "partOfSpeech": "v.",
        "vietnamese": "chứng minh, minh họa, cho thấy",
        "ipaUs": "/ˈdem.ən.streɪt/",
        "ipaUk": "/ˈdem.ən.streɪt/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "remainder",
        "partOfSpeech": "n.",
        "vietnamese": "người/vật còn lại, phần còn lại",
        "ipaUs": "/rɪˈmeɪn.dɚ/",
        "ipaUk": "/rɪˈmeɪn.dɚ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "matter",
        "partOfSpeech": "v.",
        "vietnamese": "quan trọng, trở thành vấn đề",
        "ipaUs": "/ˈmæt.ɚ/",
        "ipaUk": "/ˈmæt.ɚ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "essential",
        "partOfSpeech": "adj.",
        "vietnamese": "cần thiết, thiết yếu, cốt yếu",
        "ipaUs": "/ɪˈsen.ʃəl/",
        "ipaUk": "/ɪˈsen.ʃəl/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "divide",
        "partOfSpeech": "v.",
        "vietnamese": "chia ra, phân chia",
        "ipaUs": "/dɪˈvaɪd/",
        "ipaUk": "/dɪˈvaɪd/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "major",
        "partOfSpeech": "adj.",
        "vietnamese": "chủ yếu, chủ chốt, trọng đại",
        "ipaUs": "/ˈmeɪ.dʒɚ/",
        "ipaUk": "/ˈmeɪ.dʒɚ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "face",
        "partOfSpeech": "v.",
        "vietnamese": "đương đầu, đối mặt, hướng về",
        "ipaUs": "/feɪs/",
        "ipaUk": "/feɪs/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "follow",
        "partOfSpeech": "v.",
        "vietnamese": "làm theo, theo dõi, chú ý, theo kịp",
        "ipaUs": "/ˈfɑː.loʊ/",
        "ipaUk": "/ˈfɑː.loʊ/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "apparently",
        "partOfSpeech": "adv.",
        "vietnamese": "hình như, có vẻ như",
        "ipaUs": "/əˈper.ənt.li/",
        "ipaUk": "/əˈper.ənt.li/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "aware",
        "partOfSpeech": "adj.",
        "vietnamese": "biết, nhận thấy, nhận thức được",
        "ipaUs": "/əˈwer/",
        "ipaUk": "/əˈwer/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "extended",
        "partOfSpeech": "adj.",
        "vietnamese": "mở rộng, kéo dài",
        "ipaUs": "/ɪkˈsten.dɪd/",
        "ipaUk": "/ɪkˈsten.dɪd/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "accidentally",
        "partOfSpeech": "adv.",
        "vietnamese": "tình cờ, vô ý",
        "ipaUs": "/ˌæk.səˈden.təl.i/",
        "ipaUk": "/ˌæk.səˈden.təl.i/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "advisable",
        "partOfSpeech": "adj.",
        "vietnamese": "nên làm, thích hợp",
        "ipaUs": "/ədˈvaɪ.zə.bəl/",
        "ipaUk": "/ədˈvaɪ.zə.bəl/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "speak",
        "partOfSpeech": "v.",
        "vietnamese": "nói, phát biểu",
        "ipaUs": "/spiːk/",
        "ipaUk": "/spiːk/",
        "related": "",
        "example": "",
        "exampleVi": ""
      },
      {
        "english": "concerned",
        "partOfSpeech": "adj.",
        "vietnamese": "lo lắng, lo âu; có liên quan",
        "ipaUs": "/kənˈsɝːnd/",
        "ipaUk": "/kənˈsɝːnd/",
        "related": "",
        "example": "",
        "exampleVi": ""
      }
    ]
  }
];

const RELATED_BY_TOPIC = {
  'topic-regulations-2': {
    attire: 'clothing, dress: quần áo, trang phục',
    concern: 'worry, issue; concerned: lo lắng, mối quan ngại',
    exception: 'exclusion, special case: ngoại lệ',
    comply: 'obey, follow, adhere: tuân thủ',
    regulation: 'rule, requirement, code: quy định, quy tắc',
    policy: 'rule, guideline: chính sách, quy chế',
    severely: 'strictly, harshly: nghiêm khắc, gay gắt',
    refrain: 'abstain, avoid: kiềm chế, tránh',
    access: 'entry, permission; accessible: quyền truy cập, tiếp cận',
    thoroughly: 'carefully, completely: kỹ lưỡng, hoàn toàn',
    revise: 'amend, modify; revision: sửa đổi, duyệt lại',
    approval: 'authorization, consent: sự chấp thuận, phê duyệt',
    form: 'type, document; create: hình thức, biểu mẫu, tạo thành',
    immediately: 'promptly, right away: ngay lập tức',
    procedure: 'process, method: quy trình, thủ tục',
    negative: 'adverse, unfavorable: tiêu cực, bất lợi',
    mandate: 'order, authorize; requirement: mệnh lệnh, ủy quyền',
    effect: 'result, impact; implement: hiệu lực, tác động',
    drastically: 'sharply, radically: mạnh mẽ, triệt để',
    'according to': 'based on, in line with: theo, căn cứ theo',
    standard: 'criterion, norm: tiêu chuẩn, chuẩn mực',
    constant: 'continuous, steady: liên tục, không đổi',
    obligation: 'duty, responsibility: nghĩa vụ, trách nhiệm',
    authorize: 'permit, approve: cho phép, ủy quyền',
    prohibit: 'ban, forbid: cấm, ngăn chặn',
    habit: 'routine, custom: thói quen, tập quán',
    restrict: 'limit, constrain: giới hạn, hạn chế',
    code: 'rule, law: bộ luật, quy định',
    adhere: 'comply, stick to: tuân thủ, bám sát',
    permission: 'approval, consent: sự cho phép',
    approach: 'method; come near: phương pháp, tiếp cận',
    act: 'action; law: hành động, đạo luật',
    inspection: 'examination, review: sự kiểm tra, thanh tra',
    arrangement: 'plan, preparation: sự sắp xếp, chuẩn bị',
    enable: 'allow, permit: cho phép, làm cho có thể',
    legislation: 'law, statute: pháp luật, sự làm luật',
    compensation: 'payment, reimbursement: sự đền bù, bồi thường',
    ban: 'prohibition; prohibit: lệnh cấm, cấm',
    abolish: 'eliminate, cancel: bãi bỏ, hủy bỏ',
    enforce: 'implement, apply: thi hành, làm cho có hiệu lực',
  },
  'topic-office-work-3': {
    accustomed: 'used to, familiar with: quen với, thành thói quen',
    demanding: 'difficult, challenging: đòi hỏi cao, khắt khe',
    colleague: 'coworker, associate: đồng nghiệp',
    division: 'department, section: bộ phận, phòng ban',
    request: 'ask, appeal; requirement: yêu cầu, thỉnh cầu',
    efficiently: 'effectively, productively: hiệu quả',
    submit: 'hand in, file: nộp, đệ trình',
    directly: 'straight, immediately: trực tiếp, ngay',
    remind: 'notify, prompt: nhắc nhở',
    instruct: 'guide, direct: hướng dẫn, chỉ thị',
    sample: 'specimen, example: mẫu, ví dụ',
    notify: 'inform, announce: thông báo, cho biết',
    perform: 'carry out, conduct: thực hiện, thi hành',
    assignment: 'task, duty: nhiệm vụ, việc được giao',
    entire: 'whole, complete: toàn bộ, trọn vẹn',
    extension: 'prolongation, expansion: gia hạn, mở rộng',
    attendance: 'presence, participation: sự tham gia, có mặt',
    absolutely: 'completely, definitely: hoàn toàn, chắc chắn',
    delegate: 'assign, authorize: giao phó, ủy quyền',
    attentively: 'carefully, closely: chăm chú, thận trọng',
    supervision: 'oversight, management: sự giám sát',
    revision: 'change, amendment: sự sửa lại, duyệt lại',
    reluctantly: 'unwillingly, hesitantly: miễn cưỡng',
    acquaint: 'familiarize, inform: làm quen, làm cho biết',
    convey: 'communicate, deliver: truyền đạt, chuyển tải',
    check: 'inspect, verify: kiểm tra, xác nhận',
    file: 'submit, archive: trình lên, lưu hồ sơ',
    oversee: 'supervise, monitor: giám sát, quan sát',
    concentrate: 'focus, pay attention: tập trung, chú tâm',
    corporation: 'company, firm: công ty, tập đoàn',
    manage: 'supervise, handle: quản lý, xử lý',
    monitor: 'supervise, track; screen: giám sát, màn hình',
    deserve: 'merit, be worthy of: xứng đáng',
    release: 'publish, issue; launch: phát hành, ra mắt',
    electronically: 'digitally, online: bằng điện tử',
    workshop: 'seminar, training session: hội thảo, buổi đào tạo',
    headquarters: 'head office, main office: trụ sở chính',
    involved: 'engaged, concerned: có tham gia, liên quan',
    lax: 'careless, loose: lỏng lẻo, thiếu nghiêm túc',
    procrastinate: 'delay, put off: trì hoãn, chần chừ',
    assume: 'suppose, take on: giả sử, đảm đương',
    combined: 'joint, merged: được kết hợp, tổng hợp',
    voluntarily: 'willingly, by choice: tự nguyện',
    assist: 'help, support: trợ giúp, hỗ trợ',
    satisfied: 'pleased, content: hài lòng, thỏa mãn',
    responsible: 'accountable, in charge: có trách nhiệm',
    occasionally: 'sometimes, now and then: thỉnh thoảng',
    employee: 'staff member, worker: nhân viên, người lao động',
    conduct: 'carry out, manage: tiến hành, chỉ đạo',
    agree: 'consent, approve: đồng ý, nhất trí',
    supervise: 'oversee, manage: giám sát',
    direct: 'guide, instruct: hướng dẫn, chỉ đạo',
    assign: 'allocate, delegate: phân công, giao phó',
    formal: 'official, proper: chính thức, trang trọng',
    remove: 'delete, eliminate: xóa bỏ, dẹp bỏ',
    collect: 'gather, compile: thu thập, tập hợp',
    coordinate: 'organize, arrange: điều phối, sắp xếp',
    hardly: 'barely, scarcely: hiếm khi, gần như không',
    leading: 'main, top: hàng đầu, chủ đạo',
    exclusive: 'private, sole: riêng biệt, độc quyền',
    intention: 'purpose, aim: ý định, mục đích',
    disturbing: 'troubling, disruptive: gây xáo trộn, làm phiền',
    foster: 'encourage, promote: thúc đẩy, bồi dưỡng',
    skillfully: 'expertly, adeptly: khéo léo, thành thạo',
    widely: 'broadly, extensively: rộng rãi',
    accomplish: 'complete, achieve: hoàn thành, đạt được',
    undertake: 'take on, assume: đảm nhận, tiếp quản',
    manner: 'way, method: cách thức, lối',
    neutrality: 'impartiality, objectivity: tính trung lập',
    personnel: 'staff, employees: nhân sự, nhân viên',
    confidential: 'private, secret: bí mật, cẩn mật',
    abstract: 'theoretical, vague: trừu tượng, mơ hồ',
    directory: 'listing, address book: danh bạ, sổ địa chỉ',
    adjust: 'modify, adapt: điều chỉnh, làm cho thích hợp',
    transform: 'change, convert: biến đổi, thay đổi',
    respectful: 'polite, courteous: tôn trọng, lễ phép',
    duplicate: 'copy, replica: bản sao',
    contrary: 'opposite, reverse: sự trái ngược',
    accountable: 'responsible, answerable: chịu trách nhiệm',
    engage: 'participate, involve: tham gia, thu hút',
    timely: 'prompt, on time: kịp thời, đúng lúc',
    realistically: 'practically, pragmatically: theo thực tế',
    promptly: 'immediately, quickly: nhanh chóng, ngay lập tức',
    accessible: 'reachable, available: có thể tiếp cận',
    implement: 'carry out, enforce: thi hành, thực hiện',
    feedback: 'response, comment: phản hồi, nhận xét',
    outstanding: 'excellent, unresolved: nổi bật, chưa giải quyết',
    inform: 'notify, tell: thông báo, báo tin',
    announcement: 'notice, statement: thông báo, thông cáo',
    fulfill: 'satisfy, complete: đáp ứng, hoàn thành',
    outline: 'summary, plan; sketch: dàn ý, phác thảo',
    explain: 'clarify, describe: giải thích, giảng giải',
    overview: 'summary, outline: tổng quan, khái quát',
    matter: 'issue, topic; be important: vấn đề, quan trọng',
    replacement: 'substitute, successor: sự thay thế',
    expertise: 'skill, proficiency: chuyên môn, sự tinh thông',
    demonstrate: 'show, prove: chứng minh, minh họa',
    remainder: 'rest, remaining part: phần còn lại',
    essential: 'necessary, vital: thiết yếu, cần thiết',
    divide: 'split, separate: chia ra, phân chia',
    major: 'main, significant: chủ yếu, quan trọng',
    face: 'confront, deal with: đối mặt, đương đầu',
    follow: 'obey, track: làm theo, theo dõi',
    apparently: 'seemingly, evidently: có vẻ như, hình như',
    aware: 'conscious, informed: nhận biết, nhận thức',
    extended: 'prolonged, expanded: kéo dài, mở rộng',
    accidentally: 'unintentionally, by chance: vô tình, tình cờ',
    advisable: 'recommended, suitable: nên làm, thích hợp',
    speak: 'talk, address: nói, phát biểu',
    concerned: 'worried, involved: lo lắng, có liên quan',
  },
};

function extraWord(english, partOfSpeech, vietnamese, ipaUs, ipaUk = ipaUs, related = '') {
  return {
    english,
    partOfSpeech,
    vietnamese,
    ipaUs,
    ipaUk,
    related,
    example: '',
    exampleVi: '',
  };
}

const ADDITIONAL_SEEDED_TOPICS = [
  {
    id: 'topic-leisure-community-4',
    title: 'Topic 4: Leisure Time, Community',
    source: 'topic 4.pdf',
    words: [
      extraWord('collection', 'n.', 'bộ sưu tập, sự thu thập, sự quyên góp', '/kəˈlek.ʃən/', '/kəˈlek.ʃən/', 'collect (v): thu thập, gom; collector (n): người sưu tầm'),
      extraWord('exhibition', 'n.', 'cuộc triển lãm, sự trưng bày', '/ek.səˈbɪʃ.ən/', '/ek.sɪˈbɪʃ.ən/', 'exhibit (v/n): trưng bày, vật trưng bày'),
      extraWord('live', 'adj.', 'phát sóng trực tiếp, sống', '/laɪv/', '/laɪv/', 'alive, living: đang sống; live broadcast: phát sóng trực tiếp'),
      extraWord('popular', 'adj.', 'nổi tiếng, phổ biến', '/ˈpɑː.pjə.lɚ/', '/ˈpɒp.jə.lər/', 'liked, preferred, favorite: được yêu thích'),
      extraWord('donation', 'n.', 'sự quyên góp, từ thiện, sự tặng', '/doʊˈneɪ.ʃən/', '/dəʊˈneɪ.ʃən/', 'donate (v): quyên góp; donor (n): người quyên góp'),
      extraWord('present', 'v.', 'trình bày, giới thiệu', '/prɪˈzent/', '/prɪˈzent/', 'introduce, show: trình bày, giới thiệu'),
      extraWord('present', 'adj.', 'có mặt, hiện diện, hiện tại, hiện thời', '/ˈprez.ənt/', '/ˈprez.ənt/', 'presently (adv): bây giờ; presenter (n): diễn giả'),
      extraWord('required', 'adj.', 'cần thiết, được yêu cầu, phải có', '/rɪˈkwaɪərd/', '/rɪˈkwaɪəd/', 'mandatory, necessary: bắt buộc, cần thiết'),
      extraWord('succeed', 'v.', 'nối tiếp, kế tiếp; thành công', '/səkˈsiːd/', '/səkˈsiːd/', 'success (n): sự thành công; successful (adj): thành công'),
      extraWord('subscription', 'n.', 'sự đăng ký, sự thuê bao, mua định kỳ', '/səbˈskrɪp.ʃən/', '/səbˈskrɪp.ʃən/', 'subscribe (v): đăng ký, đặt mua'),
      extraWord('appear', 'v.', 'xuất hiện, trình diện', '/əˈpɪr/', '/əˈpɪər/', 'appearance (n): vẻ ngoài; disappear (v): biến mất'),
      extraWord('accompany', 'v.', 'đi cùng ai đó, kèm theo', '/əˈkʌm.pə.ni/', '/əˈkʌm.pə.ni/', 'go with, come with: đi cùng, kèm theo'),
      extraWord('edition', 'n.', 'sự phát hành, sự xuất bản, lần in, phiên bản', '/ɪˈdɪʃ.ən/', '/ɪˈdɪʃ.ən/', 'issue, version: ấn bản, phiên bản'),
      extraWord('specifically', 'adv.', 'cụ thể, rõ ràng, đặc trưng', '/spəˈsɪf.ɪ.kəl.i/', '/spəˈsɪf.ɪ.kəl.i/', 'particularly, clearly: cụ thể, đặc biệt'),
      extraWord('informative', 'adj.', 'nhiều thông tin, có kiến thức, bổ ích', '/ɪnˈfɔːr.mə.tɪv/', '/ɪnˈfɔː.mə.tɪv/', 'inform (v): thông báo; information (n): thông tin'),
      extraWord('note', 'v.', 'ghi chú, lưu ý', '/noʊt/', '/nəʊt/', 'notice, record: ghi nhận, lưu ý'),
      extraWord('note', 'n.', 'bản ghi nhớ, ghi chú', '/noʊt/', '/nəʊt/', 'memo, record: ghi chú, bản ghi'),
      extraWord('beneficial', 'adj.', 'có lợi, có ích', '/ˌben.əˈfɪʃ.əl/', '/ˌben.ɪˈfɪʃ.əl/', 'benefit (n/v): lợi ích, có lợi; harmful: có hại'),
      extraWord('upcoming', 'adj.', 'sắp đến, sắp tới', '/ˈʌpˌkʌm.ɪŋ/', '/ˈʌpˌkʌm.ɪŋ/', 'forthcoming: sắp đến'),
      extraWord('lend', 'v.', 'cho mượn, cho vay', '/lend/', '/lend/', 'borrow, rent: mượn, thuê'),
      extraWord('current', 'adj.', 'hiện thời, đang lưu hành', '/ˈkɝː.ənt/', '/ˈkʌr.ənt/', 'present, contemporary, valid: hiện tại, đương thời, có hiệu lực'),
      extraWord('local', 'adj.', 'địa phương, cục bộ', '/ˈloʊ.kəl/', '/ˈləʊ.kəl/', 'locally (adv): mang tính địa phương; locality (n): địa phương'),
      extraWord('variety', 'n.', 'sự đa dạng, giống, loại, trạng thái khác nhau', '/vəˈraɪ.ə.ti/', '/vəˈraɪ.ə.ti/', 'various (adj): đa dạng; vary (v): thay đổi'),
      extraWord('contributor', 'n.', 'người cống hiến, người đóng góp', '/kənˈtrɪb.jə.tɚ/', '/kənˈtrɪb.jə.tər/', 'contribute (v): đóng góp; contribution (n): sự đóng góp'),
      extraWord('defy', 'v.', 'thách thức, không tuân theo, bất chấp tất cả', '/dɪˈfaɪ/', '/dɪˈfaɪ/', 'defiance (n): sự thách thức, sự chống lại'),
      extraWord('fascinating', 'adj.', 'hấp dẫn, lôi cuốn, quyến rũ', '/ˈfæs.ən.eɪ.tɪŋ/', '/ˈfæs.ən.eɪ.tɪŋ/', 'fascinate (v): mê hoặc; fascination (n): sự mê hoặc'),
      extraWord('showing', 'n.', 'sự trình diễn, chứng cứ', '/ˈʃoʊ.ɪŋ/', '/ˈʃəʊ.ɪŋ/', 'show (v/n): trình chiếu, buổi diễn'),
      extraWord('celebrity', 'n.', 'người nổi tiếng', '/səˈleb.rə.ti/', '/səˈleb.rə.ti/', 'famous person, star: người nổi tiếng'),
      extraWord('improvise', 'v.', 'ứng biến, ngẫu hứng', '/ˈɪm.prə.vaɪz/', '/ˈɪm.prə.vaɪz/', 'improvisation (n): sự ứng biến'),
      extraWord('alumni', 'n.', 'cựu sinh viên', '/əˈlʌmnaɪ/', '/əˈlʌmnaɪ/', 'former students: cựu sinh viên'),
      extraWord('admission', 'n.', 'sự thú nhận, sự nhận vào, sự thu nạp', '/ədˈmɪʃ.ən/', '/ədˈmɪʃ.ən/', 'admit (v): nhận vào, thú nhận'),
      extraWord('banquet', 'n.', 'bữa tiệc lớn', '/ˈbæŋ.kwət/', '/ˈbæŋ.kwɪt/', 'feast, formal dinner: yến tiệc, tiệc lớn'),
      extraWord('anniversary', 'n.', 'lễ kỷ niệm, ngày kỷ niệm', '/ˌæn.əˈvɝː.sɚ.i/', '/ˌæn.ɪˈvɜː.sər.i/', 'commemoration: lễ kỷ niệm'),
      extraWord('rest', 'v.', 'nghỉ ngơi, thư giãn', '/rest/', '/rest/', 'relax, take a break: nghỉ ngơi'),
      extraWord('rest', 'n.', 'sự thư giãn, nghỉ ngơi; phần còn lại', '/rest/', '/rest/', 'remainder: phần còn lại'),
      extraWord('fund-raising', 'n.', 'việc gây quỹ', '/ˈfʌndˌreɪ.zɪŋ/', '/ˈfʌndˌreɪ.zɪŋ/', 'fundraise (v): gây quỹ; fundraiser (n): người/sự kiện gây quỹ'),
      extraWord('resume', 'v.', 'lấy lại, giành lại, bắt đầu lại, lại tiếp tục', '/rɪˈzuːm/', '/rɪˈzjuːm/', 'continue, restart: tiếp tục, bắt đầu lại'),
      extraWord('issue', 'n.', 'sự xuất bản, số báo, lần in; vấn đề', '/ˈɪʃ.uː/ /ˈɪs.juː/', '/ˈɪʃ.uː/ /ˈɪs.juː/', 'edition: ấn bản; problem: vấn đề'),
      extraWord('issue', 'v.', 'phát hành, cho ra mắt', '/ˈɪʃ.uː/ /ˈɪs.juː/', '/ˈɪʃ.uː/ /ˈɪs.juː/', 'distribute, publish: phát hành, xuất bản'),
      extraWord('anonymous', 'adj.', 'giấu tên, ẩn danh, nặc danh', '/əˈnɑː.nə.məs/', '/əˈnɒn.ɪ.məs/', 'unknown, unnamed: ẩn danh, không nêu tên'),
      extraWord('commit', 'v.', 'giao phó, ủy thác, cam kết, hứa', '/kəˈmɪt/', '/kəˈmɪt/', 'commitment (n): sự tận tâm, cam kết; devote: cống hiến'),
      extraWord('audience', 'n.', 'khán giả, thính giả', '/ˈɑː.di.əns/', '/ˈɔː.di.əns/', 'spectators, listeners: khán giả, người nghe'),
      extraWord('author', 'n.', 'tác giả', '/ˈɑː.θɚ/', '/ˈɔː.θər/', 'writer: nhà văn, tác giả'),
      extraWord('antique', 'n.', 'đồ cổ', '/ænˈtiːk/', '/ænˈtiːk/', 'old item, collectible: đồ cổ, vật sưu tầm'),
      extraWord('manuscript', 'n.', 'bản viết tay, bản thảo', '/ˈmæn.jə.skrɪpt/', '/ˈmæn.jə.skrɪpt/', 'draft, handwritten copy: bản thảo'),
      extraWord('advocate', 'n.', 'người ủng hộ, người biện hộ', '/ˈæd.və.kət/', '/ˈæd.və.kət/', 'supporter; opponent: người ủng hộ; đối thủ'),
    ],
  },
  {
    id: 'topic-marketing-5',
    title: 'Topic 5: Marketing',
    source: 'topic 5.pdf',
    words: [
      extraWord('survey', 'n.', 'cuộc khảo sát, cuộc thăm dò', '/ˈsɝː.veɪ/', '/ˈsɜː.veɪ/', 'poll, questionnaire: khảo sát, thăm dò'),
      extraWord('survey', 'v.', 'khảo sát', '/sɚˈveɪ/', '/səˈveɪ/ /ˈsɜː.veɪ/', 'examine, inspect: khảo sát, xem xét'),
      extraWord('analysis', 'n.', 'sự phân tích', '/əˈnæl.ə.sɪs/', '/əˈnæl.ə.sɪs/', 'analyze (v): phân tích; analyst (n): người phân tích'),
      extraWord('monopoly', 'n.', 'sự độc quyền, vật độc quyền', '/məˈnɑː.pəl.i/', '/məˈnɒp.əl.i/', 'monopolize (v): giữ độc quyền'),
      extraWord('competition', 'n.', 'sự cạnh tranh, cuộc thi', '/ˌkɑːm.pəˈtɪʃ.ən/', '/ˌkɒm.pəˈtɪʃ.ən/', 'compete (v): cạnh tranh; competitor (n): đối thủ'),
      extraWord('consistently', 'adv.', 'phù hợp, kiên định, nhất quán, luôn luôn', '/kənˈsɪs.tənt.li/', '/kənˈsɪs.tənt.li/', 'consistent (adj): nhất quán, kiên định'),
      extraWord('demand', 'n.', 'nhu cầu', '/dɪˈmænd/', '/dɪˈmɑːnd/', 'need, requirement: nhu cầu, yêu cầu'),
      extraWord('demand', 'v.', 'yêu cầu, đòi hỏi', '/dɪˈmænd/', '/dɪˈmɑːnd/', 'request, require: yêu cầu, đòi hỏi'),
      extraWord('expand', 'v.', 'mở rộng', '/ɪkˈspænd/', '/ɪkˈspænd/', 'expansion (n): sự mở rộng; expansive (adj): rộng rãi'),
      extraWord('advanced', 'adj.', 'tiên tiến, cao cấp', '/ədˈvænst/', '/ədˈvɑːnst/', 'advance (v): tăng lên, thúc đẩy; advancement (n): sự tiến bộ'),
      extraWord('postpone', 'v.', 'trì hoãn, hoãn lại', '/poʊstˈpoʊn/', '/pəʊstˈpəʊn/ /pəstˈpəʊn/', 'delay, put off: trì hoãn'),
      extraWord('additional', 'adj.', 'thêm vào, bổ sung vào', '/əˈdɪʃ.ən.əl/', '/əˈdɪʃ.ən.əl/', 'addition (n): phép cộng; additive (n): chất phụ gia'),
      extraWord('buy', 'v.', 'mua', '/baɪ/', '/baɪ/', 'purchase: mua'),
      extraWord('examine', 'v.', 'xem xét, kiểm tra, điều tra', '/ɪɡˈzæm.ɪn/', '/ɪɡˈzæm.ɪn/', 'inspect, analyze: kiểm tra, phân tích'),
      extraWord('effective', 'adj.', 'hiệu quả, có hiệu lực', '/əˈfek.tɪv/', '/ɪˈfek.tɪv/', 'efficient, useful: hiệu quả, hữu ích'),
      extraWord('like', 'v.', 'thích', '/laɪk/', '/laɪk/', 'prefer, enjoy: thích, ưa chuộng'),
      extraWord('especially', 'adv.', 'đặc biệt là', '/ɪˈspeʃ.əl.i/', '/ɪˈspeʃ.əl.i/', 'particularly, specially: đặc biệt'),
      extraWord('closely', 'adv.', 'sát sao, kỹ càng, chặt chẽ', '/ˈkloʊs.li/', '/ˈkləʊs.li/', 'carefully, narrowly: sát sao, kỹ lưỡng'),
      extraWord('reserve', 'v.', 'đặt trước, giữ lại', '/rɪˈzɝːv/', '/rɪˈzɜːv/', 'book, set aside: đặt trước, dành riêng'),
      extraWord('cooperate', 'v.', 'hợp tác', '/koʊˈɑː.pə.reɪt/', '/kəʊˈɒp.ər.eɪt/', 'collaborate, work together: hợp tác'),
      extraWord('vary', 'v.', 'thay đổi, khác nhau', '/ˈver.i/', '/ˈver.i/', 'differ, change: khác nhau, thay đổi'),
      extraWord('consecutive', 'adj.', 'liên tiếp, liên tục', '/kənˈsek.jə.tɪv/', '/kənˈsek.jə.tɪv/', 'successive, in a row: liên tiếp'),
      extraWord('expectation', 'n.', 'sự kỳ vọng, sự mong đợi', '/ˌek.spekˈteɪ.ʃən/', '/ˌek.spekˈteɪ.ʃən/', 'expect (v): mong đợi; expected (adj): được kỳ vọng'),
      extraWord('raise', 'v.', 'nâng lên, tăng lên, gây quỹ', '/reɪz/', '/reɪz/', 'increase, collect funds: tăng, gây quỹ'),
      extraWord('extremely', 'adv.', 'cực kỳ, hết sức', '/ɪkˈstriːm.li/', '/ɪkˈstriːm.li/', 'very, highly: rất, cực kỳ'),
      extraWord('affect', 'v.', 'ảnh hưởng đến', '/əˈfekt/', '/əˈfekt/', 'influence, impact: ảnh hưởng'),
      extraWord('probable', 'adj.', 'có khả năng, có thể xảy ra', '/ˈprɑː.bə.bəl/', '/ˈprɒb.ə.bəl/', 'likely, possible: có khả năng'),
      extraWord('focus', 'n./v.', 'trọng tâm; tập trung', '/ˈfoʊ.kəs/', '/ˈfəʊ.kəs/', 'concentrate, emphasis: tập trung, trọng tâm'),
      extraWord('seasonal', 'adj.', 'theo mùa, thời vụ', '/ˈsiː.zən.əl/', '/ˈsiː.zən.əl/', 'season (n): mùa; seasonally (adv): theo mùa'),
      extraWord('impact', 'n.', 'tác động, ảnh hưởng', '/ˈɪm.pækt/', '/ˈɪm.pækt/', 'effect, influence: tác động, ảnh hưởng'),
      extraWord('comparison', 'n.', 'sự so sánh', '/kəmˈper.ɪ.sən/', '/kəmˈpær.ɪ.sən/', 'compare (v): so sánh; comparable (adj): có thể so sánh'),
      extraWord('gap', 'n.', 'khoảng cách, khoảng trống', '/ɡæp/', '/ɡæp/', 'space, difference: khoảng trống, khoảng cách'),
      extraWord('mounting', 'adj.', 'đang tăng lên, ngày càng nhiều', '/ˈmaʊn.tɪŋ/', '/ˈmaʊn.tɪŋ/', 'increasing, growing: tăng lên'),
      extraWord('reflective', 'adj.', 'phản ánh, suy tư', '/rɪˈflek.tɪv/', '/rɪˈflek.tɪv/', 'reflect (v): phản ánh; thoughtful: suy tư'),
      extraWord('respondent', 'n.', 'người trả lời khảo sát', '/rɪˈspɑːn.dənt/', '/rɪˈspɒn.dənt/', 'participant, interviewee: người trả lời'),
      extraWord("do one's utmost", 'phr.', 'làm hết sức, cố gắng hết mình', "/duː wʌnz ˈʌt.moʊst/", "/duː wʌnz ˈʌt.məʊst/", 'try one’s best: cố gắng hết sức'),
      extraWord('appreciate', 'v.', 'đánh giá cao, cảm kích', '/əˈpriː.ʃi.eɪt/', '/əˈpriː.ʃi.eɪt/', 'value, be grateful: trân trọng, biết ơn'),
      extraWord('demonstration', 'n.', 'sự trình diễn, sự minh họa', '/ˌdem.ənˈstreɪ.ʃən/', '/ˌdem.ənˈstreɪ.ʃən/', 'demonstrate (v): chứng minh, minh họa'),
      extraWord('target', 'n.', 'mục tiêu, đối tượng', '/ˈtɑːr.ɡɪt/', '/ˈtɑː.ɡɪt/', 'goal, objective: mục tiêu'),
      extraWord('publicize', 'v.', 'quảng bá, công khai', '/ˈpʌb.lə.saɪz/', '/ˈpʌb.lɪ.saɪz/', 'advertise, promote: quảng bá'),
      extraWord('campaign', 'n.', 'chiến dịch', '/kæmˈpeɪn/', '/kæmˈpeɪn/', 'marketing campaign, drive: chiến dịch'),
      extraWord('marginal', 'adj.', 'nhỏ, không đáng kể, sát mức', '/ˈmɑːr.dʒɪ.nəl/', '/ˈmɑː.dʒɪ.nəl/', 'minor, slight: nhỏ, không đáng kể'),
      extraWord('influence', 'n./v.', 'sự ảnh hưởng; ảnh hưởng', '/ˈɪn.flu.əns/', '/ˈɪn.flu.əns/', 'affect, impact: ảnh hưởng, tác động'),
      extraWord('instantly', 'adv.', 'ngay lập tức', '/ˈɪn.stənt.li/', '/ˈɪn.stənt.li/', 'immediately, at once: ngay lập tức'),
      extraWord('creative', 'adj.', 'sáng tạo', '/kriˈeɪ.tɪv/', '/kriˈeɪ.tɪv/', 'innovative, imaginative: sáng tạo'),
      extraWord('aggressively', 'adv.', 'mạnh mẽ, quyết liệt', '/əˈɡres.ɪv.li/', '/əˈɡres.ɪv.li/', 'assertively, forcefully: quyết liệt'),
      extraWord('strategy', 'n.', 'chiến lược', '/ˈstræt.ə.dʒi/', '/ˈstræt.ə.dʒi/', 'plan, approach: kế hoạch, chiến lược'),
      extraWord('indicate', 'v.', 'chỉ ra, biểu thị', '/ˈɪn.də.keɪt/', '/ˈɪn.dɪ.keɪt/', 'show, suggest: chỉ ra, cho thấy'),
      extraWord('attract', 'v.', 'thu hút', '/əˈtrækt/', '/əˈtrækt/', 'appeal to, draw: thu hút'),
      extraWord('experience', 'n.', 'kinh nghiệm, trải nghiệm', '/ɪkˈspɪr.i.əns/', '/ɪkˈspɪə.ri.əns/', 'knowledge, encounter: kinh nghiệm, trải nghiệm'),
      extraWord('analyze', 'v.', 'phân tích', '/ˈæn.əl.aɪz/', '/ˈæn.əl.aɪz/', 'examine, study: phân tích, nghiên cứu'),
      extraWord('subscribe', 'v.', 'đăng ký, đặt mua', '/səbˈskraɪb/', '/səbˈskraɪb/', 'subscription (n): sự đăng ký, thuê bao'),
      extraWord('means', 'n.', 'phương tiện, cách thức', '/miːnz/', '/miːnz/', 'method, way: cách thức, phương tiện'),
      extraWord('prefer', 'v.', 'thích hơn, ưa hơn', '/prɪˈfɝː/', '/prɪˈfɜːr/', 'favor, choose: thích hơn, chọn'),
      extraWord('advantage', 'n.', 'lợi thế, ưu điểm', '/ədˈvæn.tɪdʒ/', '/ədˈvɑːn.tɪdʒ/', 'benefit, edge: lợi thế, ưu điểm'),
      extraWord('advise', 'v.', 'khuyên, tư vấn', '/ədˈvaɪz/', '/ədˈvaɪz/', 'recommend, counsel: khuyên, tư vấn'),
      extraWord('steadily', 'adv.', 'đều đặn, vững vàng', '/ˈsted.əl.i/', '/ˈsted.əl.i/', 'consistently, gradually: đều đặn, dần dần'),
      extraWord('necessarily', 'adv.', 'nhất thiết, tất yếu', '/ˈnes.ə.ser.ɪl.i/', '/ˈnes.ə.ser.ɪl.i/', 'inevitably, always: tất yếu, nhất thiết'),
      extraWord('detect', 'v.', 'phát hiện, nhận ra', '/dɪˈtekt/', '/dɪˈtekt/', 'discover, identify: phát hiện, xác định'),
      extraWord('favorably', 'adv.', 'một cách thuận lợi, tán thành', '/ˈfeɪ.vɚ.ə.bli/', '/ˈfeɪ.vər.ə.bli/', 'positively, approvingly: tích cực, thuận lợi'),
      extraWord('cover', 'v.', 'bao gồm, che phủ, đưa tin; chi trả', '/ˈkʌv.ɚ/', '/ˈkʌv.ər/', 'include, pay for, report on: bao gồm, chi trả, đưa tin'),
      extraWord('majority', 'n.', 'đa số, phần lớn', '/məˈdʒɑː.rə.ti/', '/məˈdʒɒr.ə.ti/', 'most, greater part: đa số, phần lớn'),
      extraWord('adopt', 'v.', 'áp dụng, chấp nhận', '/əˈdɑːpt/', '/əˈdɒpt/', 'accept, implement: chấp nhận, áp dụng'),
      extraWord('largely', 'adv.', 'phần lớn, chủ yếu', '/ˈlɑːrdʒ.li/', '/ˈlɑːdʒ.li/', 'mostly, mainly: phần lớn, chủ yếu'),
      extraWord('less', 'adv./adj.', 'ít hơn', '/les/', '/les/', 'not as much, fewer: ít hơn'),
      extraWord('effort', 'n.', 'nỗ lực, cố gắng', '/ˈef.ɚt/', '/ˈef.ət/', 'attempt, endeavor: nỗ lực'),
      extraWord('incentive', 'n.', 'động lực, sự khuyến khích', '/ɪnˈsen.tɪv/', '/ɪnˈsen.tɪv/', 'motivation, encouragement: động lực'),
      extraWord('need', 'n./v.', 'nhu cầu; cần', '/niːd/', '/niːd/', 'requirement, require: nhu cầu, cần'),
      extraWord('advertisement', 'n.', 'quảng cáo', '/æd.vɝːˈtaɪz.mənt/', '/ədˈvɜː.tɪs.mənt/', 'ad, advertising: quảng cáo'),
      extraWord('customer', 'n.', 'khách hàng', '/ˈkʌs.tə.mɚ/', '/ˈkʌs.tə.mər/', 'client, buyer: khách hàng, người mua'),
      extraWord('aim', 'n./v.', 'mục tiêu; nhắm tới', '/eɪm/', '/eɪm/', 'goal, target: mục tiêu'),
      extraWord('introduce', 'v.', 'giới thiệu', '/ˌɪn.trəˈduːs/', '/ˌɪn.trəˈdʒuːs/', 'present, launch: giới thiệu, ra mắt'),
      extraWord('absence', 'n.', 'sự vắng mặt, sự thiếu vắng', '/ˈæb.səns/', '/ˈæb.səns/', 'lack, nonattendance: sự thiếu, vắng mặt'),
      extraWord('forward', 'v.', 'chuyển tiếp, gửi chuyển', '/ˈfɔːr.wɚd/', '/ˈfɔː.wəd/', 'send on, pass along: chuyển tiếp'),
      extraWord('forward', 'adv./adj.', 'về phía trước, tiến lên', '/ˈfɔːr.wɚd/', '/ˈfɔː.wəd/', 'ahead, onward: về phía trước'),
      extraWord('contemporary', 'adj.', 'đương thời, hiện đại', '/kənˈtem.pə.rer.i/', '/kənˈtem.pər.ər.i/', 'current, modern: hiện đại, đương thời'),
      extraWord('discussion', 'n.', 'cuộc thảo luận', '/dɪˈskʌʃ.ən/', '/dɪˈskʌʃ.ən/', 'conversation, debate: thảo luận'),
      extraWord('initial', 'adj.', 'ban đầu, đầu tiên', '/ɪˈnɪʃ.əl/', '/ɪˈnɪʃ.əl/', 'first, beginning: ban đầu'),
      extraWord('resolve', 'v.', 'giải quyết, quyết tâm', '/rɪˈzɑːlv/', '/rɪˈzɒlv/', 'solve, settle: giải quyết'),
      extraWord('intensify', 'v.', 'tăng cường, trở nên mạnh hơn', '/ɪnˈten.sə.faɪ/', '/ɪnˈten.sɪ.faɪ/', 'strengthen, increase: tăng cường'),
      extraWord('disregard', 'v./n.', 'bỏ qua, coi thường; sự không để ý', '/ˌdɪs.rɪˈɡɑːrd/', '/ˌdɪs.rɪˈɡɑːd/', 'ignore, neglect: bỏ qua, xem nhẹ'),
      extraWord('mastermind', 'n./v.', 'người chủ mưu; điều hành, lập kế hoạch', '/ˈmæs.tɚ.maɪnd/', '/ˈmɑː.stə.maɪnd/', 'planner, organizer: người lập kế hoạch'),
    ],
  },
  {
    id: 'topic-economy-6',
    title: 'Topic 6: Economy',
    source: 'topic 6.pdf',
    words: [
      extraWord('dramatically', 'adv.', 'đột ngột, đáng kể', '/drəˈmæt.ɪ.kəl.i/', '/drəˈmæt.ɪ.kəl.i/', 'dramatic (adj): kịch tính, đột ngột; substantially: đáng kể'),
      extraWord('unstable', 'adj.', 'không ổn định, không bền vững', '/ʌnˈsteɪ.bəl/', '/ʌnˈsteɪ.bəl/', 'stable: ổn định'),
      extraWord('rapidly', 'adv.', 'nhanh chóng, mau lẹ', '/ˈræp.ɪd.li/', '/ˈræp.ɪd.li/', 'rapid (adj): nhanh chóng; rapidity (n): sự nhanh chóng'),
      extraWord('assert', 'v.', 'khẳng định, quả quyết, đòi', '/əˈsɝːt/', '/əˈsɜːt/', 'insist, declare: khẳng định, tuyên bố'),
      extraWord('analyst', 'n.', 'nhà phân tích', '/ˈæn.ə.lɪst/', '/ˈæn.ə.lɪst/', 'analyze (v): phân tích; analysis (n): sự phân tích, bản phân tích'),
      extraWord('potential', 'adj.', 'tiềm năng, tiềm tàng, có khả năng', '/poʊˈten.ʃəl/', '/pəˈten.ʃəl/', 'potential (n): tiềm lực, tiềm năng'),
      extraWord('remain', 'v.', 'vẫn, vẫn còn, duy trì, ở lại', '/rɪˈmeɪn/', '/rɪˈmeɪn/', 'remainder (n): phần còn lại; remaining (adj): còn lại'),
      extraWord('limited', 'adj.', 'hạn chế, có giới hạn', '/ˈlɪm.ɪ.tɪd/', '/ˈlɪm.ɪ.tɪd/', 'limit (n/v): giới hạn; limited offer: ưu đãi có giới hạn'),
      extraWord('particular', 'adj.', 'cụ thể, riêng biệt, đặc biệt', '/pɚˈtɪk.jə.lɚ/', '/pəˈtɪk.jə.lər/', 'in particular: đặc biệt, nói riêng'),
      extraWord('evenly', 'adv.', 'đều, đồng đều, công bằng', '/ˈiː.vən.li/', '/ˈiː.vən.li/', 'even (adj): bằng phẳng, đều, công bằng'),
      extraWord('pleased', 'adj.', 'hài lòng, vui mừng', '/pliːzd/', '/pliːzd/', 'be pleased to do: sẵn lòng làm gì; satisfied: hài lòng'),
      extraWord('period', 'n.', 'thời kỳ, giai đoạn, khoảng thời gian', '/ˈpɪr.i.əd/', '/ˈpɪə.ri.əd/', 'era, term: thời kỳ, giai đoạn'),
      extraWord('industry', 'n.', 'ngành công nghiệp, ngành kinh doanh', '/ˈɪn.də.stri/', '/ˈɪn.də.stri/', 'industrial (adj): thuộc công nghiệp; industrious (adj): cần cù'),
      extraWord('likely', 'adj.', 'có khả năng, có thể xảy ra', '/ˈlaɪ.kli/', '/ˈlaɪ.kli/', 'likelihood (n): khả năng; unlikely: không chắc xảy ra'),
      extraWord('prospect', 'n.', 'triển vọng, khả năng thành công', '/ˈprɑː.spekt/', '/ˈprɒs.pekt/', 'prospective (adj): tương lai, về sau'),
      extraWord('lead', 'v.', 'dẫn dắt, lãnh đạo, dẫn đến', '/liːd/', '/liːd/', 'leading (adj): dẫn đầu; lead to: dẫn đến'),
      extraWord('economical', 'adj.', 'kinh tế, tiết kiệm', '/ˌiː.kəˈnɑː.mɪ.kəl/ /ek.əˈnɑː.mɪ.kəl/', '/ˌiː.kəˈnɒm.ɪ.kəl/ /ek.əˈnɒm.ɪ.kəl/', 'economic: thuộc về kinh tế; economy (n): nền kinh tế; extravagant: phung phí'),
      extraWord('fairly', 'adv.', 'công bằng; khá, vừa phải, hợp lý', '/ˈfer.li/', '/ˈfeə.li/', 'fair (adj): công bằng; quite, reasonably: khá, vừa phải'),
      extraWord('director', 'n.', 'giám đốc, người chỉ đạo', '/daɪˈrek.tɚ/ /dɪˈrek.tɚ/', '/daɪˈrek.tər/ /dɪˈrek.tər/', 'direction (n): lời hướng dẫn; direct (v): gửi, hướng tới'),
      extraWord('substitute', 'n.', 'người thay thế, vật thay thế', '/ˈsʌb.stə.tuːt/', '/ˈsʌb.stɪ.tʃuːt/', 'substitute (v): thay thế; substitute A with B: thay A bằng B'),
      extraWord('implication', 'n.', 'sự hàm ý, ngụ ý, ảnh hưởng', '/ˌɪm.pləˈkeɪ.ʃən/', '/ˌɪm.plɪˈkeɪ.ʃən/', 'imply (v): ngụ ý; implied (adj): được ngụ ý'),
      extraWord('prosperity', 'n.', 'sự thịnh vượng, sự phồn vinh', '/prɑːˈsper.ə.ti/', '/prɒsˈper.ə.ti/', 'prosper (v): phát đạt; prosperous (adj): thịnh vượng'),
      extraWord('promising', 'adj.', 'đầy hứa hẹn, có triển vọng', '/ˈprɑː.mɪ.sɪŋ/', '/ˈprɒm.ɪ.sɪŋ/', 'promise (n/v): lời hứa, hứa; prospective: triển vọng'),
      extraWord('stagnant', 'adj.', 'trì trệ, đình trệ, không phát triển', '/ˈstæɡ.nənt/', '/ˈstæɡ.nənt/', 'stagnate (v): đình trệ; sluggish: uể oải, suy thoái'),
      extraWord('brisk', 'adj.', 'sôi động, phát đạt, nhanh nhẹn', '/brɪsk/', '/brɪsk/', 'strong, lively: mạnh mẽ, sống động; quick, rapid: nhanh chóng'),
      extraWord('soar', 'v.', 'tăng vọt, bay vút lên', '/sɔːr/', '/sɔːr/', 'plummet: rơi, lao thẳng xuống'),
      extraWord('fall', 'v.', 'rơi, giảm xuống', '/fɑːl/', '/fɔːl/', 'decrease, drop: giảm'),
      extraWord('evidence', 'n.', 'bằng chứng, chứng cứ', '/ˈev.ə.dəns/', '/ˈev.ɪ.dəns/', 'evident (adj): rõ ràng; evidently (adv): hiển nhiên'),
      extraWord('indicator', 'n.', 'chỉ số, dấu hiệu', '/ˈɪn.də.keɪ.tɚ/', '/ˈɪn.dɪ.keɪ.tər/', 'indicate (v): biểu thị, cho biết; indication (n): dấu hiệu'),
      extraWord('boom', 'n.', 'sự bùng nổ, tiếng nổ lớn', '/buːm/', '/buːm/', 'economic boom: bùng nổ kinh tế; decrease: giảm'),
      extraWord('boost', 'v.', 'thúc đẩy, tăng cường, làm tăng', '/buːst/', '/buːst/', 'boost (n): sự tăng giá, sự nổi tiếng'),
      extraWord('costly', 'adj.', 'tốn kém, đắt đỏ', '/ˈkɑːst.li/', '/ˈkɒst.li/', 'expensive, high-priced: đắt đỏ'),
      extraWord('drastic', 'adj.', 'mạnh mẽ, quyết liệt, nghiêm trọng', '/ˈdræs.tɪk/', '/ˈdræs.tɪk/', 'severe, extreme: nghiêm trọng, cực đoan'),
      extraWord('impede', 'v.', 'cản trở, ngăn cản', '/ɪmˈpiːd/', '/ɪmˈpiːd/', 'impediment (n): trở ngại; facilitate: tạo điều kiện'),
      extraWord('adversity', 'n.', 'nghịch cảnh, hoàn cảnh bất lợi', '/ədˈvɝː.sə.ti/', '/ədˈvɜː.sə.ti/', 'adverse (adj): bất lợi, ngược'),
      extraWord('consequence', 'n.', 'hậu quả, kết quả, tầm quan trọng', '/ˈkɑːn.sə.kwəns/', '/ˈkɒn.sɪ.kwəns/', 'consequential (adj): do hậu quả, tự đắc'),
      extraWord('thrive', 'v.', 'phát triển mạnh, phát đạt, thịnh vượng', '/θraɪv/', '/θraɪv/', 'prosper, flourish: phát triển mạnh, phát đạt'),
      extraWord('depression', 'n.', 'sự suy thoái, tình trạng suy thoái, sự sụt giảm', '/dɪˈpreʃ.ən/', '/dɪˈpreʃ.ən/', 'slump, recession: sự ế ẩm, tình trạng suy thoái'),
      extraWord('dwindle', 'v.', 'giảm dần, thu nhỏ lại', '/ˈdwɪn.dəl/', '/ˈdwɪn.dəl/', 'diminish: giảm bớt, thu nhỏ'),
    ],
  },
  {
    id: 'topic-shopping-7',
    title: 'Topic 7: Shopping',
    source: 'topic 7.pdf',
    words: [
      extraWord('purchase', 'v.', 'mua, mua hàng', '/ˈpɝː.tʃəs/', '/ˈpɜː.tʃəs/', 'purchase (n): việc mua hàng; buy: mua'),
      extraWord('affordable', 'adj.', 'phải chăng, có thể chi trả được', '/əˈfɔːr.də.bəl/', '/əˈfɔː.də.bəl/', 'afford (v): có đủ khả năng; reasonable: hợp lý; expensive: đắt tiền'),
      extraWord('exactly', 'adv.', 'chính xác, đúng', '/ɪɡˈzækt.li/', '/ɪɡˈzækt.li/', 'exact (adj): chính xác; precisely: đúng, chính xác'),
      extraWord('charge', 'n.', 'phí, khoản tiền phải trả', '/tʃɑːrdʒ/', '/tʃɑːdʒ/', 'charge (v): thu phí, tính phí; expense: chi phí'),
      extraWord('notice', 'n.', 'thông báo, chú ý', '/ˈnoʊ.tɪs/', '/ˈnəʊ.tɪs/', 'notice (v): chú ý, nhận biết; notification (n): thông báo'),
      extraWord('experience', 'n.', 'kinh nghiệm, trải nghiệm', '/ɪkˈspɪr.i.əns/', '/ɪkˈspɪə.ri.əns/', 'experienced (adj): có kinh nghiệm; expertise: chuyên môn'),
      extraWord('instruction', 'n.', 'sự hướng dẫn, lời chỉ dẫn', '/ɪnˈstrʌk.ʃən/', '/ɪnˈstrʌk.ʃən/', 'instructional (adj): thuộc hướng dẫn, chỉ bảo'),
      extraWord('expert', 'n.', 'chuyên gia', '/ˈek.spɝːt/', '/ˈek.spɜːt/', 'expert (adj): thành thạo, chuyên môn; expertly (adv): thành thạo'),
      extraWord('refund', 'n.', 'sự hoàn tiền, khoản tiền hoàn lại', '/ˈriː.fʌnd/', '/ˈriː.fʌnd/', 'refundable (adj): có thể hoàn trả; a full refund: hoàn tiền toàn bộ'),
      extraWord('subscriber', 'n.', 'người đăng ký, thuê bao', '/səbˈskraɪ.bɚ/', '/səbˈskraɪ.bər/', 'subscription (n): sự đăng ký định kỳ; subscribe (v): đăng ký'),
      extraWord('delivery', 'n.', 'sự giao hàng, sự phân phối', '/dɪˈlɪv.ɚ.i/', '/dɪˈlɪv.ər.i/', 'deliver (v): giao, phân phối'),
      extraWord('price', 'n.', 'giá, giá cả', '/praɪs/', '/praɪs/', 'reduced price: giá đã giảm; retail price: giá bán lẻ'),
      extraWord('offer', 'v.', 'đề nghị, cung cấp, tạo cơ hội', '/ˈɑː.fɚ/', '/ˈɒf.ər/', 'offer (n): lời đề nghị, ưu đãi; provide: cung cấp'),
      extraWord('carefully', 'adv.', 'một cách cẩn thận, kỹ càng', '/ˈker.fəl.i/', '/ˈkeə.fəl.i/', 'care (n): sự chăm sóc; careful (adj): cẩn thận; carelessly: bất cẩn'),
      extraWord('benefit', 'n.', 'lợi ích, quyền lợi', '/ˈben.ə.fɪt/', '/ˈben.ɪ.fɪt/', 'benefit (v): được hưởng lợi; beneficial (adj): có lợi; disadvantage: bất lợi'),
      extraWord('exclusively', 'adv.', 'riêng, độc quyền, duy nhất', '/ɪkˈskluː.sɪv.li/', '/ɪkˈskluː.sɪv.li/', 'exclusive (adj): dành riêng, độc quyền; solely: duy nhất'),
      extraWord('description', 'n.', 'sự mô tả, bản mô tả', '/dɪˈskrɪp.ʃən/', '/dɪˈskrɪp.ʃən/', 'describe (v): miêu tả; account: bản báo cáo, sự miêu tả'),
      extraWord('relatively', 'adv.', 'tương đối, khá', '/ˈrel.ə.tɪv.li/', '/ˈrel.ə.tɪv.li/', 'relative (adj): có liên quan, cân xứng; relate (v): liên quan'),
      extraWord('preparation', 'n.', 'sự chuẩn bị', '/ˌprep.əˈreɪ.ʃən/', '/ˌprep.ərˈeɪ.ʃən/', 'prepare (v): chuẩn bị; preparatory (adj): chuẩn bị'),
      extraWord('alter', 'v.', 'thay đổi, sửa đổi', '/ˈɑːl.tɚ/', '/ˈɒl.tər/', 'alteration (n): sự thay đổi; change, modify: thay đổi, sửa đổi'),
      extraWord('apply', 'v.', 'nộp đơn, áp dụng, ứng dụng', '/əˈplaɪ/', '/əˈplaɪ/', 'application (n): đơn xin, sự áp dụng; applicant (n): ứng viên'),
      extraWord('mutually', 'adv.', 'lẫn nhau, cùng nhau', '/ˈmjuː.tʃu.ə.li/', '/ˈmjuː.tʃu.ə.li/', 'mutual (adj): lẫn nhau; mutually beneficial: đôi bên cùng có lợi'),
      extraWord('method', 'n.', 'phương pháp, cách thức', '/ˈmeθ.əd/', '/ˈmeθ.əd/', 'approach: phương pháp; a method of payment: phương thức thanh toán'),
      extraWord('area', 'n.', 'khu vực, vùng, lĩnh vực', '/ˈer.i.ə/', '/ˈeə.ri.ə/', 'site: bãi đất, lô đất; region: vùng'),
      extraWord('officially', 'adv.', 'một cách chính thức', '/əˈfɪʃ.əl.i/', '/əˈfɪʃ.əl.i/', 'official (adj): chính thức; formally: chính thức'),
      extraWord('qualify', 'v.', 'đủ điều kiện, đạt tiêu chuẩn', '/ˈkwɑː.lə.faɪ/', '/ˈkwɒl.ɪ.faɪ/', 'qualification (n): năng lực, trình độ; qualified (adj): đủ điều kiện'),
      extraWord('valid', 'adj.', 'hợp lệ, có hiệu lực, có giá trị', '/ˈvæl.ɪd/', '/ˈvæl.ɪd/', 'invalid: không hợp lệ; valid receipts: hóa đơn hợp lệ'),
      extraWord('installment', 'n.', 'khoản trả góp, kỳ trả góp', '/ɪnˈstɑːl.mənt/', '/ɪnˈstɔːl.mənt/', 'pay by/in installments: trả góp'),
      extraWord('auction', 'n.', 'cuộc đấu giá, sự bán đấu giá', '/ˈɑːk.ʃən/', '/ˈɔːk.ʃən/', 'sell at auction: bán đấu giá'),
      extraWord('receipt', 'n.', 'biên lai, hóa đơn, sự nhận được', '/rɪˈsiːt/', '/rɪˈsiːt/', 'receive (v): nhận; original/valid receipt: biên lai gốc/hợp lệ'),
      extraWord('clearance', 'n.', 'sự cho phép, sự thông quan, bán xả hàng', '/ˈklɪr.əns/', '/ˈklɪə.rəns/', 'authorization: sự cho phép; clearance sale: bán xả toàn bộ hàng'),
      extraWord('spare', 'adj.', 'dự trữ, dự phòng, thừa', '/speər/', '/speər/', 'spare change: tiền lẻ dự phòng; extra: thêm, dư'),
      extraWord('authentic', 'adj.', 'xác thực, thật, đáng tin', '/ɑːˈθen.tɪk/', '/ɔːˈθen.tɪk/', 'genuine: thật, chính cống; fake: giả'),
      extraWord('warranty', 'n.', 'bảo hành, giấy bảo hành', '/ˈwɔːr.ən.ti/', '/ˈwɒr.ən.ti/', 'under warranty: trong thời gian bảo hành'),
      extraWord('fabric', 'n.', 'vải, chất liệu vải', '/ˈfæb.rɪk/', '/ˈfæb.rɪk/', 'material, cloth: vật liệu, vải'),
      extraWord('vendor', 'n.', 'người bán, nhà cung cấp', '/ˈven.dɚ/', '/ˈven.dər/', 'seller, supplier: người bán, nhà cung cấp'),
      extraWord('acceptable', 'adj.', 'có thể chấp nhận được, phù hợp', '/əkˈsept.ə.bəl/', '/əkˈsept.ə.bəl/', 'fine: được, ổn; unacceptable: không chấp nhận được'),
      extraWord('desire', 'n.', 'mong muốn, khát khao', '/dɪˈzaɪr/', '/dɪˈzaɪər/', 'desire (v): ao ước; desirable (adj): đáng khao khát'),
      extraWord('redeemable', 'adj.', 'có thể mua lại, có thể quy đổi', '/rɪˈdiː.mə.bəl/', '/rɪˈdiː.mə.bəl/', 'redeem (v): mua lại, quy đổi'),
      extraWord('consumption', 'n.', 'sự tiêu thụ, lượng tiêu thụ', '/kənˈsʌmp.ʃən/', '/kənˈsʌmp.ʃən/', 'consume (v): tiêu thụ; consumer (n): người tiêu dùng'),
    ],
  },
];

function withRelatedWords(topic) {
  const relatedByWord = RELATED_BY_TOPIC[topic.id] || {};

  return {
    ...topic,
    words: topic.words.map((word) => ({
      ...word,
      related: relatedByWord[word.english.toLowerCase()] || word.related || '',
    })),
  };
}

export const EXTRA_SEEDED_TOPICS = [...RAW_EXTRA_SEEDED_TOPICS, ...ADDITIONAL_SEEDED_TOPICS].map(withRelatedWords);
